# https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard

require:
  - standard
  - rubocop-performance
  - rubocop-rspec

# Use the defaults from https://github.com/testdouble/standard.
inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop_local.yml

AllCops:
  TargetRubyVersion: 3.0
  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  UseCache: true
  CacheRootDirectory: .
  MaxFilesInCache: 10000
