# frozen_string_literal: true

source "https://rubygems.org"

gem "rspec", "~> 3.11"
gem "guard-rspec", "~> 4.7"

group :development, :test do
  gem "standard", "~> 1.16", require: false
  gem "rubocop-rspec", "~> 2.13", require: false
end
