build:
	echo "find the day you want to run"

day-3:
	cp input-day3.txt input.txt
	python mcpower-day3_2.py

day-4:
	cp input-day4.txt input.txt
	python mcpower-day4_1.py
	ruby tomd-day4_2.rb

day-5:
	ruby tomd-day5_1.rb
	ruby tomd-day5_2.rb

day-6:
	ruby tomd-day6_1.rb
	ruby tomd-day6_2.rb

day-8:
	echo "wrong answers"
	ruby -Itomd-lib tomd-day8_1.rb
	ruby -Itomd-lib tomd-day8_2.rb
	cp input-day8.txt input.txt
	python mcpower-day8_1.py
	python mcpower-day8_2.py

day-9:
	echo "wrong answers"
	ruby -Itomd-lib tomd-day9_1.rb
	ruby -Itomd-lib tomd-day9_2.rb
	echo "right answers"
	cp input-day9.txt input.txt
	python mcpower-day9.py

day-10:
	ruby tomd-day10_1.rb
	ruby tomd-day10_2.rb

day-11:
	ruby -Itomd-lib tomd-day11_1.rb
	ruby -Itomd-lib tomd-day11_2.rb

day-12:
	ruby tomd-day12_1.rb
	ruby tomd-day12_2.rb

day-13:
	echo "wrong answers"
	ruby -Itomd-lib tomd-day13_1.rb
	ruby -Itomd-lib tomd-day13_2.rb
	echo "right answer"
	cp input-day13.txt input.txt
	python mcpower-day13_1.py
	echo "wrong answer"
	python mcpower-day13_2.py
	echo "right answer"
	ruby astley92-day13_2.rb

day-15:
	ruby -Itomd-lib tomd-day15_1.rb
	echo "runs forever => 2829"
	ruby -Itomd-lib tomd-day15_2.rb

day-16:
	ruby tomd-day16_1.rb
	ruby tomd-day16_2.rb

day-17:
	echo "wrong answer"
	ruby -Itomd-lib tomd-day17.rb
	echo "right answers"
	cp input-day17.txt input.txt
	python mcpower-day17_1.py
	python mcpower-day17_2.py

day-18:
	ruby tomd-day18_1.rb
	ruby tomd-day18_2.rb

day-19:
	cp input-day19.txt input.txt
	python mcpower-day19_1.py
	python mcpower-day19_2.py

day-20:
	cp input-day20.txt input.txt
	python mcpower-day20_1.py
	python mcpower-day20_2.py

day-22:
	echo "right answer part 2 1225064738333321"
	python imnimo-day22.py

