# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec", "~> 3.11"

gem "puma", "~> 5.6"
gem "rack", "~> 2.2"
gem "sinatra", "~> 2.2"

gem "sidekiq", "~> 6.5"
