[package]
name = "simple-url-fetch"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.6.0"
http-body-util = "0.1.1"
hyper = { version = "1.3.1", features = ["full"] }
hyper-util = { version = "0.1.5", features = ["full"] }
tokio = { version = "1.38.0", features = ["full"] }
