source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.7'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :test do
  gem "capybara", "~> 3.37"
  gem "selenium-webdriver", "~> 4.5"
  gem "webdrivers", "~> 5.2"
end

group :development do
  gem 'listen', '~> 3.3'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem "dry-monads", "~> 1.4"
gem "dry-rails", "~> 0.5.0", :github => "dry-rb/dry-rails"
gem "rom-rails", "~> 2.3"
gem "rom-sql", "~> 3.5"

gem "pg", "~> 1.4"

gem "dotenv-rails", "~> 2.8"
gem "pry-rails", "~> 0.3.9"
gem "rspec-rails", "~> 5.1"


gem "dry-validation", "~> 1.8"
