# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rubocop", "~> 1.25"
gem "rubocop-performance", "~> 1.13"
gem "rubocop-rspec", "~> 2.8"

gem "sidekiq", "~> 6.4"

gem "puma", "~> 5.6"
gem "rack", "~> 2.2"
gem "sinatra", "~> 2.2"
