set shell := ["zsh", "-uc"]

# Colors
START   := "\\u001b["
RED     := "\\u001b[31m"
GREEN   := "\\u001b[32m"
YELLOW  := "\\u001b[33m"
BLUE    := "\\u001b[34m"
MAGENTA := "\\u001b[35m"
BOLD    := "\\u001b[1m"
RESET   := "\\u001b[0m"

_default:
    @just --list --unsorted

# setup the rustwedev database
@setup-db:
    psql rustwebdev -XtAc "\q" > /dev/null 2>&1 || \
        psql -c "create database rustwebdev;" && \
        echo "rustwebdev created"
    psql rustwebdev -c "\dt"

QID := "1"
EMAIL_ID := `date +"%S"`
# demo CRUD
demo-crud:
    @echo "{{START}}32;5;7m𝔸𝕌𝕋ℍ 🪪🔐 register{{RESET}}"
    echo '{ \
    "email":"email{{EMAIL_ID}}@example.com", \
    "password":"clear_text_password" \
    }' | curl --json @- localhost:1337/registration
    @echo
    @echo "{{RED}}above create should return the :id{{RESET}}"
    @echo "{{RED}}and :email{{RESET}}"
    @echo

    @echo "{{START}}32;5;7m𝔸𝕌𝕋ℍ 🪪🔐 check account{{RESET}}"
    psql rustwebdev -XtAc "SELECT * FROM accounts"

    @echo "{{START}}32;5;7m𝔸𝕌𝕋ℍ 🪪🔐 login{{RESET}}"

    # https://stackoverflow.com/a/58598185/1564635
    cap () { tee /tmp/capture.out; } && \
    echo '{ \
    "email":"email{{EMAIL_ID}}@example.com", \
    "password":"clear_text_password" \
    }' | curl --json @- localhost:1337/login | cap
    @echo

    @echo "{{YELLOW}}attempting to use id: {{QID}} but should get this from create{{RESET}}"

    @echo "{{GREEN}}🄻 ist{{RESET}}"
    curl localhost:1337/questions
    @echo

    @echo "{{GREEN}}🄲 reate{{RESET}}"
    ret () { cat /tmp/capture.out; } && \
    TOKEN=`ret | tr -d '"'` && \
    curl localhost:1337/questions \
        -H "Authorization: ${TOKEN}" \
        -H "Content-Type: application/json" \
        -d '{"id":"{{QID}}","title":"the title","content":"the content","tags":["home","work"]}'
    @echo
    @echo "{{RED}}above create should return the :id{{RESET}}"

    @echo "{{GREEN}}\n🅁 ead{{RESET}}"
    curl "localhost:1337/question/{{QID}}"

    @echo "{{GREEN}}\n🅄 pdate{{RESET}}"
    ret () { cat /tmp/capture.out; } && \
    TOKEN=`ret | tr -d '"'` && \
    curl -X PUT \
        "localhost:1337/questions/{{QID}}" \
        -H "Authorization: ${TOKEN}" \
        -H 'content-type: application/json' \
        -d '{"id":{{QID}},"title":"NOT","content":"NOT","tags":["OLD","NEW"]}'
    @echo

    # check again
    curl "localhost:1337/question/{{QID}}"

    @echo "\n{{GREEN}}🅰 🅳 🅳 {{YELLOW}}𝓐𝓷𝓼𝔀𝓮𝓻{{RESET}}"
    curl localhost:1337/answers \
        -H "Content-Type: application/json" \
        -d '{"id":1,"content":"also via json","question_id":"{{QID}}"}'
    @echo
    @echo "{{RED}}above fails as only form encoding is supported{{RESET}}"

    @echo "\n{{GREEN}}🅰 🅳 🅳 {{YELLOW}}𝓐𝓷𝓼𝔀𝓮𝓻{{RESET}}"
    curl localhost:1337/answers \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "id=1" \
        --data-urlencode "content=also from a form" \
        --data-urlencode "question_id={{QID}}"

    @echo "\n{{GREEN}}🅶 🅴 🆃 {{YELLOW}}𝓐𝓷𝓼𝔀𝓮𝓻𝓼{{RESET}}"
    curl "localhost:1337/questions/{{QID}}/answers"

    @echo "{{GREEN}}\n🄳 elete{{RESET}}"
    ret () { cat /tmp/capture.out; } && \
    TOKEN=`ret | tr -d '"'` && \
    curl -X DELETE "localhost:1337/questions/{{QID}}" \
        -H "Authorization: ${TOKEN}" \

    @echo "{{GREEN}}\n🄻 ist{{RESET}}"
    curl localhost:1337/questions

# cleanup and remove rustwebdev database
@clean:
    psql rustwebdev -c '\q' > /dev/null 2>&1 && \
        psql -c "drop database rustwebdev;" || \
        echo "rustwebdev alrady dropped"
