[env:nano]
platform = atmelavr
framework = arduino
monitor_speed = 115200
; board = nanoatmega328new
; upload_port = /dev/cu.usbserial-310
; monitor_port = /dev/cu.usbserial-310
board = nanoatmega328
upload_port = /dev/cu.usbmodemFX2348N1
monitor_port = /dev/cu.usbmodemFX2348N1
